---
title: "Financial Status Report"
author: "Clayton Yochum"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
---

```{r global-defaults, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r dependencies}
library(googlesheets)
library(dplyr)
library(zoo)
library(knitr)
library(scales)
library(tidyr)
library(ggplot2)
```


```{r read-and-clean}
# read in the workbook
workbook <- gs_url("https://docs.google.com/spreadsheets/d/1nga7F6MC3eQ3JdrPG9yV7ZBsipPOxmZLlvidrNeFEQM/")

# cleanup Primary
# remove lines without shortcodes
primary_df <- workbook %>%
  gs_read(ws = "Primary") %>%
  mutate(Shortcode = as.integer(gsub("[^0-9]", "", Shortcode))) %>%
  filter(!is.na(Shortcode)) %>%
  mutate_each(funs(gsub("[^0-9/]", "", .) %>% as.Date(format = "%m/%d/%Y")), contains("Date")) %>%
  mutate_each(funs(gsub("[^0-9.]", "", .) %>% as.numeric), TotalAwardAmount, CurrentYearDirect, CurrentYearIndirect) %>% 
  select(
    Shortcode,
    ContractName,
    ContractStartDate,
    ContractEndDate,
    CurrentYearStartDate,
    CurrentYearEndDate,
    TotalAwardAmount,
    CurrentYearDirect,
    CurrentYearIndirect
  )

# cleanup FinancialStatus
# only want most recent month for each shortcode
financial_df <- workbook %>%
  gs_read(ws = "FinancialStatus") %>%
  mutate(MonthYear = as.yearmon(MonthYear, format = "%b%y")) %>%  # convert to first-of-month dates
  group_by(Shortcode) %>%
  arrange(desc(MonthYear)) %>% 
  slice(1) %>%
  ungroup %>%
  select(
    Shortcode,
    MonthYear,
    Spent,
    Encumbered,
    AmountRemaining
  )

# join together
df <- inner_join(primary_df, financial_df, by = "Shortcode") %>%
  mutate(ContractName = factor(ContractName, levels = ContractName))  # factor in order given
```


```{r format-dollars}
format_dollars <- function(df, cols = c()) {
  cols <- cols %>%
    c("TotalAwardAmount", "CurrentYearDirect", "CurrentYearIndirect", "Spent", "Encumbered", "AmountRemaining") %>%
    intersect(names(df))
  
  df %>% mutate_each_(funs(dollar), cols)
}
```


## Accounting Verification

Let's verify the money allocated to each project matches up with the Spent, Encumbered, and Amount Remaining pulled from the most recent University-provided reports; we expect "Unaccounted" to be zero:

```{r unaccounted}
df %>%
  select(ContractName, CurrentYearDirect, MonthYear, Spent, Encumbered, AmountRemaining) %>%
  mutate(Unaccounted = (CurrentYearDirect - (Spent + Encumbered + AmountRemaining)) %>% round(2)) %>%
  format_dollars("Unaccounted") %>% 
  kable
```


## Visual Representation

```{r gathered-df}
gathered_df <- df %>%
  select(ContractName, CurrentYearStartDate, CurrentYearEndDate, Spent, Encumbered, Remaining = AmountRemaining) %>%
  gather("category", "dollars", Spent, Encumbered, Remaining) %>%
  mutate(
    ContractName = factor(ContractName, levels = rev(levels(ContractName))),
    category     = factor(category, levels = c("Spent", "Encumbered", "Remaining"))
  ) %>%
  group_by(ContractName) %>% 
  mutate(
    length = as.integer(CurrentYearEndDate - CurrentYearStartDate) * (dollars / sum(dollars)),
    start  = ifelse(category == "Spent", CurrentYearStartDate,
                    ifelse(category == "Encumbered", CurrentYearStartDate + lag(length, 1, order_by = category),
                           ifelse(category == "Remaining", CurrentYearStartDate + lag(length, 1, order_by = category) + lag(length, 2, order_by = category), NA)
             )
    ) %>% as.Date,
    end = start + length
  ) %>% 
  ungroup %>% 
  arrange(ContractName, category)
```


```{r charts, fig.width=8}
ggplot(gathered_df, aes(x = ContractName, y = dollars, fill = category)) +
  geom_bar(position = "stack", stat = 'identity') +
  coord_flip() +
  ggtitle("Spent/Encumbered/Remaining by Contract") +
  xlab("Contract") +
  ylab("Amount (in USD)")

ggplot(gathered_df, aes(color = category)) +
  geom_segment(aes(x = start, xend = end, y = ContractName, yend = ContractName), size = 10) +
  geom_vline(xintercept = as.integer(Sys.Date())) +
  ggtitle("Spending Progress Gantt Chart") +
  xlab("Date") +
  ylab("Contract")

```

